local Lockouts_Def = {}

function Lockouts_Def.Lockout_Globals()
	return {
		{ "podisease_lockout", "Plane of Disease"},
		{ "codecay_lockout", "Crypt of Decay"},
		{ "potorment_lockout", "Torment, The Plane of Pain"},
		{ "povalor_lockout", "Plane of Valor"},
		{ "poinnovation_lockout", "Plane of Innovation"},
		{ "ponightmareb_lockout", "The Lair of Terris Thule"},
		{ "hohonora_villaage", "The Halls of Honor: Villagers"},
		{ "hohonora_maiden", "The Halls of Honor: Maidens"},
		{ "hohonora_dragon", "The Halls of Honor: Dragon"},
		{ "hohonorb_lockout", "The Temple of Marr"},
		{ "potactics_tallon", "Drunder, the Fortress of Zek: Tallon Zek"},
		{ "potactics_vallon", "Drunder, the Fortress of Zek: Vallon Zek"},
		{ "potactics_rallos", "Drunder, the Fortress of Zek: Rallos Zek"},
		{ "bothunder_lockout", "Bastion of Thunder"},
		{ "solrotower_jiva", "The Tower of Solusek Ro: Jiva"},
		{ "solrotower_arlyxir", "The Tower of Solusek Ro: Arlyxir"},
		{ "solrotower_dresolik", "The Tower of Solusek Ro: Dresolik "},
		{ "solrotower_xuzl", "The Tower of Solusek Ro: Xuzl"},
		{ "solrotower_rizlona", "The Tower of Solusek Ro: Rizlona"},
		{ "solrotower_lockout", "The Tower of Solusek Ro"},
		{ "poair_wind", "The Plane of Air: Wind Ring"},
		{ "poair_smoke", "The Plane of Air: Smoke Ring"},
		{ "poair_mist", "The Plane of Air: Mist Ring"},
		{ "poair_dust", "The Plane of Air:Dust Ring"},
		{ "poair_xegony", "The Plane of Air: Xegony"},
		{ "poeartha_vine", "Vegarlson, the Earthen Badlands: Vine"},
		{ "poeartha_mud", "Vegarlson, the Earthen Badlands: Mud"},
		{ "poeartha_stone", "Vegarlson, the Earthen Badlands: Stone"},
		{ "poeartha_dust", "Vegarlson, the Earthen Badlands: Dust"},
		{ "poeartha_arbitor", "Vegarlson, the Earthen Badlands: Arbitor"},
		{ "poearthb_lockout", "Ragrax, Stronghold of the Twelve"},
		{ "pofire_lockout", "Plane of Fire"},
		{ "powater_lockout", "Plane of Water"},
		{ "potimeb_lockout", "Plane of Time"},
		{ "lockout_ikky_g1", "Ikkinz Group Trial #1: Singular Might"},
		{ "lockout_ikky_g2", "Ikkinz Group Trial #2: Twin Struggles"},
		{ "lockout_ikky_g3", "Ikkinz Group Trial #3: Tri-Fates"},
		{ "ikkylockout3", "Ikkinz Raid #1: Chambers of Righteousness"},
		{ "ikkylockout4", "Ikkinz Raid #2: Chambers of Glorification"},
		{ "ikkylockout5", "Ikkinz Raid #3: Chambers of Transcendence"},
		{ "ikkylockout6", "Ikkinz Raid #4: Chambers of Destruction"},
		{ "uqualockout", "Uqua, the Ocean God Chantry"},
		{ "Ink_Kelekdrix", "Kelekdrix, Herald of Trushar" },
		{ "Ink_Mites", "Stonemite Event" },
		{ "Ink_Golems", "Inktu`Ta Golems" },
		{ "Ink_Callers", "Cursecaller Event" },
		{ "Ink_Noqufiel", "Noqufiel Event" },
		{ "Tacvi_PXK", "Tacvi: Pixtt Xxeric Kex" },
		{ "Tacvi_PKK", "Tacvi: Pixtt Kretv Krakxt" },
		{ "Tacvi_PRT", "Tacvi: Pixtt Riel Tavas" },
		{ "Tacvi_ZMKP", "Tacvi: Zun`Muram Kvxe Pirik" },
		{ "Tacvi_ZMSB", "Tacvi: Zun`Muram Shaldn Boc" },
		{ "Tacvi_ZMMD", "Tacvi: Zun`Muram Mordl Delt" },
		{ "Tacvi_ZMYV", "Tacvi: Zun`Muram Yihst Vor" },
		{ "Tacvi_TMCV", "Tacvi: Tunat`Muram Cuu Vauax" },
		{ "LDON_rujd", "LDoN Raid: Rujarkian Hills: Prison Break"},
		{ "LDON_rujg", "LDoN Raid: Rujarkian Hills: Hidden Vale of Deceit"},
		{ "mirb_50_lockout", "LDoN Raid: Miragul's Menagerie: Frozen Nightmare"},
		{ "LDON_mirg", "LDoN Raid: Miragul's Menagerie: Folly of Miragul's Ambition"},
		{ "LDON_mmcc", "LDoN Raid: Mistmoore Catacombs: Struggles within the Progeny"},
		{ "LDON_takc", "LDoN Raid: Takish-Hiz: Within the Compact" },
		{ "LDON_guke", "LDoN Raid: Deepest Guk: The Curse Reborn"},
		{ "LDON_gukg", "LDoN Raid: Deepest Guk: Ritualist of Hate"},
		{ "MPG_fear", "MPG: The Mastery of Fear"},
		{ "MPG_weaponry", "MPG: The Mastery of Weaponry"},
		{ "MPG_subversion", "MPG: The Mastery of Subversion"},
		{ "MPG_efficiency", "MPG: The Mastery of Efficiency"},
		{ "MPG_ingenuity", "MPG: The Mastery of Ingenuity"},
		{ "MPG_destruction", "MPG: The Mastery of Destruction"},
		{ "MPG_hatred", "MPG: Trial of Hatred" },
		{ "MPG_specialization", "MPG: Trial of Specialization" },
		{ "MPG_endurance", "MPG: Trial of Endurance" },
		{ "MPG_foresight", "MPG: Trial of Foresight" },
		{ "MPG_adaptation", "MPG: Trial of Adaptation" },
		{ "MPG_corruption", "MPG: Trial of Corruption" },
		{ "paladinEpicDranikCata","Dranik Catacombs A" },
		{ "Anguish_keldovan", "Anguish: Keldovan the Harrier" },
		{ "Anguish_jelvan", "Anguish: Rescuing Jelvan" },
		{ "Anguish_ture", "Anguish: Ture" },
		{ "Anguish_hanvar", "Anguish: Warden Hanvar" },
		{ "Anguish_amv", "Anguish: Arch Magus Vangl" },
		{ "Anguish_omm", "Anguish: Overlord Mata Muram" },
		{ "Anguish_lower_orb", "Anguish: Lower Globe of Discordant Energy" },
		{ "Anguish_upper_orb", "Anguish: Upper Globe of Discordant Energy" },
		{ "Anguish_augs", "Anguish: Replay Timer" }
	}
end

return Lockouts_Def;