#!/bin/sh
#echo "Checking Perl scripts..."
#find . -name "*.pl" \
#| while read s
#do
        #if ! perl -c "$s"; then
                #echo "$s is invalid."
        #fi
#done
cmd='luac';
if hash luac-5.1 2>/dev/null; then
  cmd='luac-5.1';
fi

echo "Checking Lua scripts..."
find . -name "*.lua" \
| while read s
do
        if ! `$cmd -p "$s"`; then
                echo "$s is invalid."
        fi
done
echo "Script check completed."