----------------------------------------------------------------------
-- Zone: PoJustice
-- NPC: Yventa Va`Ssula (201328)
----------------------------------------------------------------------

function event_say(e)
    if(e.message:findi("Hail")) then
        e.self:Emote("flicks her reptilian tongue at you as she glares at you in utter contempt. Her voice spills forward in a whispered hiss, 'What purpose have you here among us, free one? Do you find yourself pleased by the misery of the degenerate beings this place hosts? Or perhaps you are a bard and wish to spread the tales of our treachery as a lesson to the innocent? You know nothing if that is your wish here, for not all of us are victims of conscious convictions. Some, like myself, are held because of who we are in the innermost depths of our spirits -- something that we cannot help or change. We are condemned for that which we could not control in our lives. That is the true element of my fate here. If you do not understand or accept this, then perhaps you should speak with us and hear our [" .. eq.say_link("tales") .. "]. Learn before you base assumptions upon ignorance.");
    elseif(e.message:findi("tales")) then
		e.self:Emote("hisses again, her tongue flicking in the insipid air of her cell in swift reaction to your question, 'You wish to hear my tale? You wish to know why I am a prisoner of this eternal, cosmic jailhouse? Well, then sit down and keep your ears focused and heart steady -- for the tale I tell you does not thirst for your pity, just your understanding as to the true [" .. eq.say_link("purpose") .. "] of this place.'");
    elseif(e.message:findi("purpose")) then
		e.self:Say("The Tribunal will judge any and all beings who have committed crimes so vile that their own people cannot deliver proper justice. As a member of the Empire of Ik, my being here is something to be respected, for I upheld my true self to the end and hold no regrets for it. I defied my empire in a way that so few were ever capable -- for I defied it not out of a yearning for rebellion or a hatred for my leaders, but my [" .. eq.say_link("how was your existence destined",false,"existence was destined") .. "] was destined for this fate.");
    elseif(e.message:findi("how was your existence destined")) then
		e.self:Say("In my years upon Norrath, I served as one of several hand-maidens to Drusilla Sathir, our Empress and governess of the eastern lands of Kunark. As well as being her guardian, I was her faithful and devoted servant from birth. The spirits deemed this life to be the one forged for my spirit. I was raised by the elder maidens of our mistress and taught from the beginning how to properly serve and devote my life and existence to her. We were all thoroughly educated in the practical arts of our people and each given the training in a specific martial role. I was trained in the ways of the shadowknight, for the spirits had forged me strong and true in both body and conviction. In this fashion, I would serve as both servant and guardian to my mistress. It was a good life, one that I pledged every fiber of my being to fulfill. It is a cruel twist of fate regarding what [" .. eq.say_link("consequences") .. "] would later befall me.");
    elseif(e.message:findi("consequences")) then
		e.self:Say("I despised my mistress. I cursed her secretly, for I believed that she disabled me from being something greater than a mere servant. I was one of the best swordsmen in the whole of the empire at that time and my instructor knew this. His hands were tied, for he had told me in secret that it was unfortunate and cruel trickery of the spirits to have placed such a strong and skillful warrior in the binds of servitude. He was a general, one of many appointed by Sathir himself to defend the empire's greatness in conquest of the continent. From that moment on, I hated my mistress in the deepest recesses of my being. I had prayed to The Faceless in secret, pleading for the chance to prove myself above this station and ascend to what I believed my proper calling to be -- a general beside Venril Sathir in the great legions of Ik.");
		e.self:Say("My prayers would be answered, though the consequence of my exploiting of the [" .. eq.say_link("opportunity") .. "] would be far beyond my most fearsome nightmares.");
    elseif(e.message:findi("opportunity")) then
		e.self:Say("My mistress would leave us on holiday to the capital of Sebilis. Only twenty of her guardians accompanied her on the venture, for the rest were commanded to remain behind and guard her personal dwellings. Whilst she was away, we were attacked by a legion of sarnak who knew the mistress -- whom the entire realm feared -- was gone. We defended the home fiercely and were victorious in the end. Three sarnak escaped us and I pursued despite the calling of my superiors. Four days later, in the Burning Wood, I caught them. We engaged in battle and two of them fell to my blade. The other fled, but not far for I shot him with a poisoned arrow and watched him die over the course of five hours. When his final breath was exhausted, a [" .. eq.say_link("vision") .. "] flooded my mind.");
    elseif(e.message:findi("vision")) then
		e.self:Say("The vision was one of blood and chaos amidst a cloud of dust and battle. Within stood a mirror and upon one side was the reflection of Iksarian might with the victory over a mighty legion of dragons. Within it, I carried a battle-worn blade and the flag of our empire, raised high in triumph. The other was one ruin and devastation and my face was nowhere to be seen. I knew the vision was one delivered to me by The Faceless -- that I would be key to the fate of the Empire of Ik and that my purpose was beyond that of a mere handmaiden. I ventured them to Karnor's castle, where I knew my mentor to be stationed. There, I confided in him the vision that I had received. He placed me before a seer -- a high shaman in the scaled mystics who had given visions to Sathir himself upon occasion. What he [" .. eq.say_link("what did he see",false,"saw") .. "] then would change the course of my life.");		
    elseif(e.message:findi("what did he see")) then
		e.self:Say("The seer saw nothing -- merely the delusions of a disenchanted handmaiden who sought greater fortune and purpose in the world. The spirits were final, he said, and their need of me was absolute in my current station. I was ordered to return to Drusilla's side, where she would deem the proper punishment for my disobedience of her orders. My escort and I reached the wilds of the Frontier Mountains. It was there that I slew him, forever altering my course from one of potential greatness to this -- a prisoner. I had shaved the scales from my face and wore a mask always to conceal the scars. I donned the colors and armor of the empire's legions in secret for many years. It was when my skills were recognized by my mentor upon the Field of Bone that I was found out. Branded a traitor by the seers for straying from my destined course, I was ritualistically disemboweled and my spirit condemned. The Tribunal would judge me in the hereafter and this is what my fate would be.");		
	end
end

function event_trade(e)
    local item_lib = require("items");
    item_lib.return_items(e.self, e.other, e.trade)
end