----------------------------------------------------------------------
-- Zone: PoJustice
-- NPC: Wurgoz (201337)
----------------------------------------------------------------------

function event_say(e)
    if(e.message:findi("Hail")) then
        e.self:Emote("tilts his head and gives a slight twitch of his eyes in quick observation of ".. e.other:GetName() .. ", 'You are free...  you are not a prisoner of this place. Interesting. Perhaps...  perhaps you would care to listen to my tale? Maybe... maybe you can give me some relief from this suffering and ease my conscience if only for a moment.");
    elseif(e.message:findi("tale")) then
		e.self:Emote("makes a quick, short motion with his webbed hands in excitement, 'Very good! Very good! Oops...  Shhh...  We should discuss this quietly. The prisoners are not supposed to speak, you see. We are here to be punished and I would not wish to jeopardize your own freedom after you've so graciously accepted my offer. Now, let me tell you that little tale -- short and sweet it is, though dark and terrible in truth.'");
	elseif(e.message:findi("truth")) then
		e.self:Say("I have been a prisoner of this place for many a year, many a year. I committed a terrible crime many years ago against my own people an... Innocent people. I regret my actions, I regret them dearly but there is nothing I can do to make right out of my ancient crimes from here. That is why I need you -- to help me, for the sake of my own conscience. Are you still willing to aid me? Will you still venture into the depths of a dark past to oblige a stranger's -- a criminals' plight through mere lending of your ear?");
	elseif(e.message:findi("i will aid you")) then
		e.self:Say("Very good! Very good! You are kind, indeed. In ancient times when the Elddar forest stood high in all of its lush, emerald beauty across the most of eastern Tunaria, my people came to the swampland known as Innothule. There, we found the trolls -- the vile, horrible, maniacal creations of The Faceless who ruled that land. We wanted only peace and to inhabit a piece of that fertile swampland without confronting the trolls directly. However, they did not feel the same as we. The trolls began to capture and use our people as slaves or consume them as food! We were horrified and took immediate action against them.");
	elseif(e.message:findi("action")) then
		e.self:Say("The frogloks came together in massive force and struck at the heart of the troll civilization to dominate the swampland. We prepared an invasion of their city that dwelled deep beneath the soggy earth of the swamp. The battle seemed to sway to the trolls' favor. I, a shaman general and advisor to our leaders, felt the pain of our people as we fell by the hundreds to troll armies. I could not stand to see our people suffer so, for we had come seeking peace. War -- all war -- hurts us most deeply within. I pleaded with our leaders to find another swampland; to leave this place to the trolls who rightfully had claimed the land before us. Their ears were deaf to me, for they saw a great evil in these lands. It had gone beyond a desire for a new homeland for our people. It had become a crusade.");
	elseif(e.message:findi("crusade")) then
		e.self:Say("Our elders sought to purge the swamplands of the trolls. We knew they were vile and truly evil in every recess of their beings, but still I could not stand by and watch a war engage. We were creatures of peace who sought only the betterment of our own people. War was not our way. A troll shaman by the name of Gkerzha approached me one eve whilst I was alone, scouting the swampland. He claimed to approach in peace and we spoke -- for the first time, troll and froglok spoke. Gkerzha claimed he wanted the same as I -- for the frogloks to leave the swampland and let the trolls alone. He seemed sincere and regretful for the loss and turmoil that infected his people as it did my own. We parted ways shortly thereafter, but he claimed he wished to make a bargain with me that would end the war peacefully.");
	elseif(e.message:findi("bargain")) then
		e.self:Say("Gkerzha and I met several times to discuss plans to bring peace to both races, for frogloks to move to another region of the swamp and for trolls to return to their lives before froglok presence. I was foolish enough to trust him, but he was cunning and knew how to invoke my sense of sorrow and yearning for peace. He brought to me three frogloks who had been taken prisoner and were used as slaves. They were in bad health, but Gkerzha said he did not wish to place his magic on them. Frogloks superstitious and we feared troll magic on us. His gesture was clever. I healed the slaves and returned them to our camp, where they recovered. I met Gkerzha again the next eve and he brought two more slaves and an ancient trollic dagger.");
	elseif(e.message:findi("dagger")) then
		e.self:Say("Gkerzha said dagger was ancient trollic weapon of legend -- belonging to the troll hero, Tjarduugh, who saved swampland from invasion by humans centuries earlier. He placed the dagger on the ground after he released slaves into my care. He said the dagger was trollic notion of peace. He said the dagger had killed many frogloks in ceremonies and made them the undead that accompanied their forces. He said that my taking of the dagger would assure that no more frogloks would be cursed to walk as the undead servants of the trolls. This was his way of showing a desire for peace. He left quickly without further explanation, the dagger still on the ground. I picked up the dagger with a cloth and put it safe in my pack. I then returned to camp with the three froglok slaves. Later that eve, the folly of my naive trust in the trolls would be revealed in a gruesome tragedy.");
	elseif(e.message:findi("tragedy")) then
		e.self:Say("The froglok camp in the south end of swamp was safe from trolls for a long time. That is where I took the slaves to recover. I stayed there and had council with the arch magi and high shaman. I wanted to show them the dagger, but as soon as it touched my skin, something changed in me. I brought the dagger to the arch magi and high shaman, and before they could act, I killed them with the dagger -- the 'gift of peace' Gkerzha had given to me. I remember going out into the camp and killing more frogloks there. I had murdered almost all of them before I was subdued and the dagger rent from me. I felt, as soon as the dagger left my hand, regret for what I had consciously done. I was taken prisoner before the council of generals and our leader. As the hearing was held, news of a greater and unforeseen devastation resulting in my foolishly placed trust reached us.");
	elseif(e.message:findi("devastation")) then
		e.self:Say("All that I had killed, including the arch magi and high shaman, had arisen as undead and were being commanded by a troll shaman. I immediately knew it to be Gkerzha. The scout said they were heading to the very camp where I was currently held. I pleaded with the council to destroy the dagger, or take it far, far away for it will cause them more suffering if they did not. They did not listen to me. I was caged and thrown into the deepest pool of the swamp, where I would either meet my fate or wait for the trial to continue. Days passed before the council returned and retrieved me from my swampy prison. They said that Gkerzha committed suicide -- invoking the dark power of Innoruuk to destroy hundreds of froglok legions. It was my fault that so many died, they said, and my judgment was beyond their abilities. I was sacrificed and my spirit sent to this place, where I would stand trial before The Tribunal. My fate is more than the elders realized it would be.");
	elseif(e.message:findi("fate")) then
		e.self:Say("Forever I am condemned to be a prisoner -- I do not protest that judgment either. But I must forever live with my guilt and know that what I have done will never be avenged. Gkerzha's spirit still wanders Norrath. I can feel it at times, taunting me when the barrier separating this plane from Norrath is weakest -- when a new criminal is brought here to be tried. I am so mournful... I regret so much. I deserve my punishment, but the wrongs I committed must be avenged.");
	end
end

function event_trade(e)
    local item_lib = require("items");
    item_lib.return_items(e.self, e.other, e.trade)
end